FORMAT: 1A
HOST: http://platform/

# Workflow Management

API to manage Workflows and Workflows instances.
All request should contain the Accept header with a value of application/hal+json


## Primed Workflow Collection [/api/primedworkflows/{?skip,limit}]
A primed workflow represents the combination of a workflow definition and any arguments required to run the workflow
Example: A workflow 'GetAllMailboxes' has been defined. It takes a tenant Id as a parameter. 
A primed workflow is the combination of the 'GetAllMailboxes' workflow and an argument for the parameter(tenandId = {xyz}).
   

### List All Primed Workflows [GET]

+ Parameters
    + skip(optional) - number of records to skipe for this page
    + limit(optional) - number of records to inclued in this page

+ Response 200 (application/json)
        
        {
            "TotalResults": 13,
            "TotalPages": 3,
            "Page": 1,
            "Skip": 0,
            "Limit": 5,
            "_links": {
                "self": {
                    "href": "/api/primedworkflows?skip=0&limit=5"
                },
                "next": {
                    "href": "/api/primedworkflows?skip=5&limit=5"
                },
                "page": {
                    "href": "/api/primedworkflows{?skip,limit}",
                    "templated": true
                },
                "_items": [
                    {
                        "href": "/api/primedworkflows/e3936a80-92fd-e611-98ec-e0c3691abae0"
                    },
                    {
                        "href": "/api/primedworkflows/10c2c0c0-94fd-e611-98ec-e0c3691abae0"
                    },
                    {
                        "href": "/api/primedworkflows/3b18fe55-b7fd-e611-98ec-e0c3691abae0"
                    },
                    {
                        "href": "/api/primedworkflows/cbf4bc69-b7fd-e611-98ec-e0c3691abae0"
                    },
                    {
                        "href": "/api/primedworkflows/ccf4bc69-b7fd-e611-98ec-e0c3691abae0"
                    }
                ]
            },
            "_embedded": {
                "_items": [
                    {
                        "Id": "e3936a80-92fd-e611-98ec-e0c3691abae0",
                        "WorkflowName": "PostMailboxesA",
                        "Arguments": "[]",
                        "_links": {
                            "self": {
                                "href": "/api/primedworkflows/e3936a80-92fd-e611-98ec-e0c3691abae0"
                            },
                            "worflow": {
                                "href": "/api/workflows/PostMailboxesA"
                            }
                        }
                    },
                    {
                        "Id": "10c2c0c0-94fd-e611-98ec-e0c3691abae0",
                        "WorkflowName": "PostMailboxesA",
                        "Arguments": "[]",
                        "_links": {
                            "self": {
                                "href": "/api/primedworkflows/10c2c0c0-94fd-e611-98ec-e0c3691abae0"
                            },
                            "worflow": {
                                "href": "/api/workflows/PostMailboxesA"
                            }
                        }
                    },
                    {
                        "Id": "3b18fe55-b7fd-e611-98ec-e0c3691abae0",
                        "WorkflowName": "PostMailboxesA",
                        "Arguments": "[]",
                        "_links": {
                            "self": {
                                "href": "/api/primedworkflows/3b18fe55-b7fd-e611-98ec-e0c3691abae0"
                            },
                            "worflow": {
                                "href": "/api/workflows/PostMailboxesA"
                            }
                        }
                    },
                    {
                        "Id": "cbf4bc69-b7fd-e611-98ec-e0c3691abae0",
                        "WorkflowName": "PostMailboxesA",
                        "Arguments": "[]",
                        "_links": {
                            "self": {
                                "href": "/api/primedworkflows/cbf4bc69-b7fd-e611-98ec-e0c3691abae0"
                            },
                            "worflow": {
                                "href": "/api/workflows/PostMailboxesA"
                            }
                        }
                    },
                    {
                        "Id": "ccf4bc69-b7fd-e611-98ec-e0c3691abae0",
                        "WorkflowName": "PostMailboxesA",
                        "Arguments": "[]",
                        "_links": {
                            "self": {
                                "href": "/api/primedworkflows/ccf4bc69-b7fd-e611-98ec-e0c3691abae0"
                            },
                            "worflow": {
                                "href": "/api/workflows/PostMailboxesA"
                            }
                        }
                    }
                ]
            }
        }

### Prime a workflow [POST]

To prime a workflow is to combine a workflow definition by name with an argument for its required parameters. 

+ Request (application/json)

        {
            "workflowName": "ExampleWorkflow",
            "arguments": [,pre 
                {
                    "name": "ExampleTenantId",
                    "stateName": "ExampleStateName",
                    "Value":"ExampleValue"
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: api/primedworkflows/id

    + Body
       
            {
                "Id": "e3936a80-92fd-e611-98ec-e0c3691abae0",
                "WorkflowName": "PostMailboxesA",
                "Arguments": "[]",
                "_links": {
                    "self": {
                    "href": "/api/primedworkflows/e3936a80-92fd-e611-98ec-e0c3691abae0"
                },
                    "worflow": {
                    "href": "/api/workflows/PostMailboxesA"
                    }
                }
            }

## Primed Workflows [/api/primedworkflows/{id}]
A primed workflow represents the combination of a workflow definition and any arguments required to run the workflow

### Get a specific instance of a Primed Workflow [GET]
+ Parameters
    + id - Valid URL id of instance

+ Response 200 (application/json)

        [
            {
                "id": "{94BC55CE-0A4F-4E96-9988-000956DA831A}",
                "workflowName": "ExampleName",
                "arguments": : "ExampleArguments",
                "_links":{
                    "self": "http://platform/api/primedworkflows/{id}",
                    "workflow": "http://platform/api/workflows/WorkflowNameExample"
                }
            }
        ]


### Update a specific instance of a Primed Workflows [PUT]
Updating a primed workflow is only allowed before a primed workflow is started.
A primed workflow can only be updated by supplying alternative arguments for it's parameters

+ Parameters
    + id - A path variable that is required for a valid URL

+ Request (application/json)

        {
            "arguments": [
                {
                    "name": "ExampleTenantId",
                    "stateName": "ExampleStateName",
                    "Value":"AlternativeExampleValue"
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/id

    + Body

            {
                "id": "{id}",
                "configurationName": "ExampleName",
                "arguments": : "ExampleArguments",
                "_links":{
                    "self": "http://platform/api/primedworkflows/94BC55CE-0A4F-4E96-9988-000956DA831A",
                    "workflow": "http://platform/api/workflows/WorkflowNameExample"
                }
            }


## Workflow Instance Collection [/api/workflowinstances/{?skip,limit}]
A workflow instance is a running workflow. 
 
### List All Workflow Instance [GET]

+ Parameters
    + skip(optional) - number of records to skipe for this page
    + limit(optional) - number of records to inclued in this page

+ Response 200 (application/json)
        
        {
            "items":[
                {
                    "id": "{D9430D11-FCD5-46DC-BFA1-04232C8679F8}",
                    "name": "ExampleName",
                    "state": "ExampleState",
                    "parentId": "null",
                    "parentState": "null",
                    "modified": "ISO Datetime example",
                    "_links":{
                        "self": "http://platform/api/workflowinstances/D9430D11-FCD5-46DC-BFA1-04232C8679F8",
                        "workflow": "http://platform/api/workflows/WorkflowNameExample",
                        "configuredWorkflow": "http://platform/api/configuredworkflows/94BC55CE-0A4F-4E96-9988-000956DA831A",
                        "monitor": "http://platform/monitors/api/D9430D11-FCD5-46DC-BFA1-04232C8679F8"
                    }
                }
            ],
            "_links":{
                "previousPage": "http://platform/workflowinstances?skip=100&limit=50"
                "nextPage": "http://platform/workflowinstances?skip=200&limit=50"
            }
        }
            

### Create a Workflow Instance [POST]
The following call creates a workflow instance

+ Request (application/json)

        {
            "configuredWorkflowId": "configuredWorkflowId",
            "parameters": [
                {
                    "Parameter1": "Parameter1Value",
                    "Parameter2": "Parameter2Value",
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: api/workflowinstances/{id}

    + Body

            {
                "id": "{D9430D11-FCD5-46DC-BFA1-04232C8679F8}",
                "name": "ExampleName",
                "state": "ExampleState",
                "parentId": "null",
                "parentState": "null",
                "modified": "ISO Datetime example",
                "_links":{
                    "self": "http://platform/workflowinstances/D9430D11-FCD5-46DC-BFA1-04232C8679F8",
                    "workflow": "http://platform/workflows/WorkflowNameExample",
                    "configuredWorkflow": "http://platform/configuredworkflows/94BC55CE-0A4F-4E96-9988-000956DA831A",
                    "monitor": "http://platform/monitors/D9430D11-FCD5-46DC-BFA1-04232C8679F8"
                }
            }

### Update a Workflow Instance [PUT]
The following call will stop/restart/pause a workflow instance

+ Request (application/json)

        {
            "command": "stop/restart/pause",
        }

+ Response 201 (application/json)

    + Headers

            Location: api/workflowinstances/{id}

    + Body

            {
                "id": "{D9430D11-FCD5-46DC-BFA1-04232C8679F8}",
                "name": "ExampleName",
                "state": "ExampleState",
                "parentId": "null",
                "parentState": "null",
                "modified": "ISO Datetime example",
                "_links":{
                    "self": "http://platform/workflowinstances/D9430D11-FCD5-46DC-BFA1-04232C8679F8",
                    "workflow": "http://platform/workflows/WorkflowNameExample",
                    "configuredWorkflow": "http://platform/configuredworkflows/94BC55CE-0A4F-4E96-9988-000956DA831A",
                    "monitor": "http://platform/monitors/D9430D11-FCD5-46DC-BFA1-04232C8679F8"
                }
            }


## Workflow Monitoring Collection [/api/monitors/{?skip,limit}]
The following endpoint should be used to monitor running workflows

### List All Workflow Monitors [GET]

+ Parameters
    + skip(optional) - number of records to skipe for this page
    + limit(optional) - number of records to inclued in this page

+ Response 200 (application/json)
        
        {
            "items":[
                {
                    "id": "{id}",
                    "runningState": "Running",
                    "currentState": "Step1",
                    "_links":{
                        "self": "http://platform/api/monitors/{workflowInstanceId}",
                        "workflow": "http://platform/api/workflows/{workflowName}",
                        "configuredWorkflow": "http://platform/api/configuredworkflows/{configuredId}",
                        "workflowInstance": "http://platform/api/workflowInstance/{workflowInstanceId}",
                        "result":{
                            "href":"http://platform/api/results/{workflowInstanceId}/{stepId}"
                            "numberOfItems":10
                        }
                    }
                }
            ],
            "_links":{
                "previousPage": "http://platform/monitors?skip=100&limit=50"
                "nextPage": "http://platform/monitors?skip=200&limit=50"
            }
        }
            


## Monitoring a single Workflow [/api/monitors/{workflowInstanceId}]

### Monitor Workflow [GET]
+ Response 200 (application/json)
        
        {
            "id": "{workflowInstanceId}",
            "runningState": "Running",
            "currentStep": "Step1",
            "currentStepId": "{stepId}",
            "_links":{
                "self": "http://platform/monitors/{workflowInstanceId}",
                "workflow": "http://platform/workflows/{workflowName}",
                "configuredWorkflow": "http://platform/configuredworkflows/{configuredId}",
                "workflowInstance": "http://platform/workflowInstance/{workflowInstanceId}",
                "result":{
                    "href":"http://platform/results/{workflowInstanceId}?stepId={stepId}"
                    "numberOfItems":10
                }
            }
        }

## Workflow Result [/api/result/{workflowInstanceId}/{?stepId,skip,limit}]
Execute the following call to get the results as generated by a step in the workflow.
The schema of the objects will be defined on the configuration of the workflow. 
The full object will be contained in the item key. 
(The sequence of items cannot be guaranteed)  

### Get Workflow Step Results [GET]

+ Response 200 (application/json)

        {
            "items":[
                {
                    "index": 150,
                    "item":{
                            "Database": "L2-EXC2010-01-ServiceAccounts",
                            "ExchangeGuid": "98072400-a1ff-4714-afed-75fa53f81347",
                            "IsMailboxEnabled": "TRUE",
                            "SamAccountName": "Administrator",
                            "ServerLegacyDN": "/o=L2/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=L2-EXC2010-01",
                            "ServerName": "l2-exc2010-01",
                            "Office": "",
                            "UserPrincipalName": "Administrator@lab.quadrotech-it.com",
                            "ArchiveDatabase": "",
                            "ArchiveGuid": "00000000-0000-0000-0000-000000000000",
                            "ArchiveName": "",
                            "ArchiveQuota": "Unlimited",
                            "ArchiveWarningQuota": "Unlimited",
                            "ArchiveDomain": "",
                            "ArchiveStatus": "None",
                            "ArchiveState": "None",
                            "DisabledArchiveDatabase": "",
                            "DisabledArchiveGuid": "00000000-0000-0000-0000-000000000000",
                            "WhenMailboxCreated": "16.04.2015 11:10",
                            "OrganizationalUnit": "l2.lab.quadrotech-it.com/Users",
                            "DisplayName": "Administrator",
                            "EmailAddresses": "smtp:Administrator@quadrotechlab3.mail.onmicrosoft.com SMTP:Administrator@lab.quadrotech-it.com smtp:Administrator@l2.lab.quadrotech-it.com",
                            "LegacyExchangeDN": "/o=L2/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=Administrator",
                            "PrimarySmtpAddress": "Administrator@lab.quadrotech-it.com",
                            "RecipientType": "UserMailbox",
                            "Name": "Administrator",
                            "Guid": "25a8be7b-a48e-4a7f-9897-4307893687f3",
                            "Id": "l2.lab.quadrotech-it.com/Users/Administrator"
                    }
                },
                {
                    "index": 151,
                    "item":{
                            "Database": "Mailbox Database 1383866539",
                            "ExchangeGuid": "46f72e4b-0174-44d4-99b8-472ef3d9378a",
                            "IsMailboxEnabled": "TRUE",
                            "SamAccountName": "SM_c821a34f4cc543dba",
                            "ServerLegacyDN": "/o=L2/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=L2-EXC2010-01",
                            "ServerName": "l2-exc2010-01",
                            "Office": "",
                            "UserPrincipalName": "DiscoverySearchMailbox{D919BA05-46A6-415f-80AD-7E09334BB852}@lab.quadrotech-it.com",
                            "ArchiveDatabase": "",
                            "ArchiveGuid": "00000000-0000-0000-0000-000000000000",
                            "ArchiveName": "",
                            "ArchiveQuota": "Unlimited",
                            "ArchiveWarningQuota": "Unlimited",
                            "ArchiveDomain": "",
                            "ArchiveStatus": "None",
                            "ArchiveState": "None",
                            "DisabledArchiveDatabase": "",
                            "DisabledArchiveGuid": "00000000-0000-0000-0000-000000000000",
                            "WhenMailboxCreated": "24.03.2015 10:38",
                            "OrganizationalUnit": "l2.lab.quadrotech-it.com/Users",
                            "DisplayName": "Discovery Search Mailbox",
                            "EmailAddresses": "smtp:DiscoverySearchMailbox{D919BA05-46A6-415f-80AD-7E09334BB852}@quadrotechlab3.mail.onmicrosoft.com SMTP:DiscoverySearchMailbox{D919BA05-46A6-415f-80AD-7E09334BB852}@lab.quadrotech-it.com smtp:DiscoverySearchMailbox{D919BA05-46A6-415f-80AD-7E09334BB852}@l2.lab.quadrotech-it.com",
                            "LegacyExchangeDN": "/o=L2/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=DiscoverySearchMailbox {D919BA05-46A6-415f-80AD-7E0933",
                            "PrimarySmtpAddress": "DiscoverySearchMailbox{D919BA05-46A6-415f-80AD-7E09334BB852}@lab.quadrotech-it.com",
                            "RecipientType": "UserMailbox",
                            "Name": "DiscoverySearchMailbox {D919BA05-46A6-415f-80AD-7E09334BB852}",
                            "Guid": "ee8f967e-d623-46ea-9927-79222ab92b83",
                            "Id": "l2.lab.quadrotech-it.com/Users/DiscoverySearchMailbox {D919BA05-46A6-415f-80AD-7E09334BB852}"
                    }
                },
            ],
            "_links":{
                "previousPage": "http://platform//api/result/{workflowInstanceId}?stepId={stepId}&skip=100&limit=50"
                "nextPage":  "http://platform//api/result/{workflowInstanceId}?stepId={stepId}&skip=200&limit=50"
            }
        }